# Generated by Django 4.1.3 on 2023-02-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('product_image', models.ImageField(upload_to='product')),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Sofa', 'Sofa'), ('Chair', 'Chair')], max_length=6, null=True)),
                ('description', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
